name: quiz_app_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.5
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.5.0

  standard_searchbar: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/Lottie/